<?php ?>

LBL_NAME: Deutsche Feiertage
LBL_HDY_DE_NEUJAHR: Neujahrstag
LBL_HDY_DE_DREIKOENIG: Heilige drei Könige
LBL_HDY_DE_VALENTINE: Valentinstag
LBL_HDY_DE_PALMSONNTAG: Palmsonntag
LBL_HDY_DE_KARFREITAG: Karfreitag
LBL_HDY_DE_OSTERN: Ostern
LBL_HDY_DE_OSTERMONTAG: Ostermontag
LBL_HDY_DE_TAGDERARBEIT: Tag der Arbeit
LBL_HDY_DE_MUTTERTAG: Muttertag
LBL_HDY_DE_AUFFAHRT: Christi Himmelfahrt
LBL_HDY_DE_PFINGSTEN: Pfingsten
LBL_HDY_DE_PFINGSTMONTAG: Pfingstmontag
LBL_HDY_DE_FRONLEICHNAM: Fronleichnam
LBL_HDY_DE_MARIAHIMMELFAHRT: Mariä Himmelfahrt
LBL_HDY_DE_NATIONALFEIERTAG: Tag der Deutschen Einheit
LBL_HDY_DE_REFORMATIONSTAG: Reformationstag
LBL_HDY_DE_ALLERHEILIGEN: Allerheiligen
LBL_HDY_DE_VOLKSTRAUERTAG: Volkstrauertag
LBL_HDY_DE_BUSSUNDBETTAG: Buß- und Bettag
LBL_HDY_DE_TOTENSONNTAG: Totensonntag
LBL_HDY_DE_NIKOLAUS: St. Nikolaus
LBL_HDY_DE_ADVENT1: Erster Advent
LBL_HDY_DE_ADVENT2: Zweiter Advent
LBL_HDY_DE_ADVENT3: Dritter Advent
LBL_HDY_DE_ADVENT4: Vierter Advent
LBL_HDY_DE_HEILIGABEND: Heilig Abend
LBL_HDY_DE_WEIHNACHTEN: Weihnachten
LBL_HDY_DE_WEIHNACHT2: 2. Weihnachtstag
LBL_HDY_DE_SILVESTER: Silvester


