<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dashletStrings['WeatherDashlet'] = array(
	'LBL_TITLE' => 'World Weather',
	'LBL_CONFIGURE_TITLE' => 'Title:',
	'LBL_DESCRIPTION' => 'Displays selected city',
	'LBL_CITY' => 'City',
    'LBL_WOEID' => 'WOEID',
    'LBL_DEGREES_UNITS' => 'Degrees Units:',
	'LBL_TODAY' => 'Today (H/L)',
	'LBL_TOMORROW' => 'Tomorrow',
	'LBL_CURRENT' => 'Current',
	'LBL_CURRENT_CONDITIONS' => 'Current Conditions',
	'LBL_BAROMETER' => 'Barometer',
	'LBL_HUMIDITY' => 'Humidity',
	'LBL_VISIBILITY' => 'Visibility',
	'LBL_WIND' => 'Wind',
	'LBL_WIND_CHILL' => 'with wind',
	'LBL_SUNRISE' => 'Sunrise',
	'LBL_SUNSET' => 'Sunset',
	'LBL_FORECAST' => 'Forecast',
	'LBL_HIGH' => 'High',
	'LBL_LOW' => 'Low',
	'LBL_UNLIMITED' => 'Unlimited',
	'LBL_AND' => 'and',
	'LBL_PRESSURE_STEADY' => 'steady',
	'LBL_PRESSURE_RISING' => 'rising',
	'LBL_PRESSURE_FALLING' => 'falling',
	'LBL_CURRENT_CITIES' => 'Current Cities:',
	'LBL_ADD_CITY' => 'Add City',
	'LBL_DISPLAY_TIME' => 'Display Times:',
	'LBL_LIST_TIME' => 'Time',
	'LBL_CLEAR' => 'Clear',
	'LBL_SEARCH' => 'Search',
	'LBL_REMOVE' => 'Remove',
	
	'LBL_WIND_DEG0' => 'N',
	'LBL_WIND_DEG45' => 'NE',
	'LBL_WIND_DEG90' => 'E',
	'LBL_WIND_DEG135' => 'SE',
	'LBL_WIND_DEG180' => 'S',
	'LBL_WIND_DEG225' => 'SW',
	'LBL_WIND_DEG270' => 'W',
	'LBL_WIND_DEG315' => 'NW',
	
	'LBL_LAST_UPDATE' => 'Last updated: {time}.',
	'LBL_VISIT_SITE' => 'Yahoo! Weather',
	
	'LBL_LOOKUP_ERROR' => 'Error performing lookup',
);
?> 